import { describe, expect, it } from "vitest";

import { mapDirectusTalent } from "@infrastructure/directus/talent/talent.mapper";

describe("mapDirectusTalent", () => {
  it("mapeia todas as colunas de um talento completo", () => {
    const row: Parameters<typeof mapDirectusTalent>[0] = {
      id: "talent-1",
      user_id: {
        id: "user-1",
        email: "ana@example.com",
        first_name: "Ana",
        last_name: "Silva",
      },
      graduation_course: "Engenharia de Software",
      graduation_institution: "UFSC",
      talent_current_skills: ["JavaScript", "TypeScript"],
      reset_count: 2,
      current_cycle_id: "cycle-1",
      current_cycle: 3,
      department: "Engineering",
      current_status: "ACTIVE",
      orchestrator_state: "READY",
      pdi_plan_ready: true,
      start_date: "2024-01-01",
      end_date: null,
      date_created: "2024-01-01",
      date_updated: "2024-02-01",
      date_deleted: null,
      phone_number: "5511999999999",
      verified_phone_number: "5511888888888",
      last_status_change_at: "2024-01-05",
      last_reset_at: "2024-01-10",
      leader_id: {
        id: 10,
        position: "Manager",
        department: "Engineering",
      },
      target_role_id: {
        id: 20,
        name: "Senior Engineer",
        description: "Responsável por liderar squads técnicos",
        date_created: "2023-12-01",
        date_updated: null,
        date_deleted: null,
        important_skills: ["liderança", "typescript"],
        success_criteria: "Entregar projetos críticos",
        talent_id: "talent-1",
        required_skills: ["Design de sistemas"],
        talent_current_skills: ["typescript"],
        match: 98,
      },
    };

    const mapped = mapDirectusTalent(row);

    expect(mapped).toEqual({
      id: "talent-1",
      userId: "user-1",
      userFirstName: "Ana",
      userLastName: "Silva",
      userEmail: "ana@example.com",
      phoneNumber: "5511999999999",
      verifiedPhoneNumber: "5511888888888",
      graduationCourse: "Engenharia de Software",
      graduationInstitution: "UFSC",
      currentSkills: ["JavaScript", "TypeScript"],
      targetRoleId: 20,
      leaderId: 10,
      resetCount: 2,
      currentCycleId: "cycle-1",
      currentCycle: 3,
      department: "Engineering",
      currentStatus: "ACTIVE",
      orchestratorState: "READY",
      pdiPlanReady: true,
      startDate: "2024-01-01",
      endDate: null,
      dateCreated: "2024-01-01",
      dateUpdated: "2024-02-01",
      dateDeleted: null,
      lastStatusChangeAt: "2024-01-05",
      lastResetAt: "2024-01-10",
      leader: {
        id: 10,
        position: "Manager",
        department: "Engineering",
      },
      targetRole: {
        id: 20,
        name: "Senior Engineer",
        description: "Responsável por liderar squads técnicos",
        dateCreated: "2023-12-01",
        dateUpdated: null,
        dateDeleted: null,
        importantSkills: ["liderança", "typescript"],
        successCriteria: "Entregar projetos críticos",
        talentId: "talent-1",
        requiredSkills: ["Design de sistemas"],
        talentCurrentSkills: ["typescript"],
        match: 98,
      },
    });
  });

  it("normaliza relações ausentes e valores primitivos", () => {
    const row: Parameters<typeof mapDirectusTalent>[0] = {
      id: "talent-2",
      talent_current_skills: "excel avançado",
      leader_id: undefined,
      target_role_id: undefined,
      user_id: undefined,
      phone_number: undefined,
      verified_phone_number: undefined,
      graduation_course: null,
      graduation_institution: undefined,
      reset_count: undefined,
      current_cycle_id: undefined,
      current_cycle: undefined,
      department: undefined,
      current_status: undefined,
      orchestrator_state: undefined,
      pdi_plan_ready: null,
      start_date: undefined,
      end_date: undefined,
      date_created: undefined,
      date_updated: undefined,
      date_deleted: undefined,
      last_status_change_at: undefined,
      last_reset_at: undefined,
    };

    const mapped = mapDirectusTalent(row);

    expect(mapped).toMatchObject({
      id: "talent-2",
      userId: null,
      userFirstName: null,
      userLastName: null,
      userEmail: null,
      phoneNumber: null,
      verifiedPhoneNumber: null,
      graduationCourse: null,
      graduationInstitution: null,
      currentSkills: "excel avançado",
      targetRoleId: null,
      leaderId: null,
      leader: null,
      targetRole: null,
      resetCount: null,
      currentCycleId: null,
      currentCycle: null,
      department: null,
      currentStatus: null,
      orchestratorState: null,
      pdiPlanReady: null,
      startDate: null,
      endDate: null,
      dateCreated: null,
      dateUpdated: null,
      dateDeleted: null,
      lastStatusChangeAt: null,
      lastResetAt: null,
    });
  });
});
